BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXX XXXXXX BBBBBBBB


BBBBB BBBBBBB
    XXXXXXXXX XXXXXX XXXXXXXXX

    XXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBXX
            BBBBBBBBBB
            FFFFFFFFFFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB