# Generated by Django 3.1.7 on 2021-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
