# Generated by Django 3.1.7 on 2021-02-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0002_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
