# Generated by Django 3.1.7 on 2021-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0006_auto_20210227_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.ManyToManyField(blank=True, to='shop_product.IPAddress'),
        ),
    ]
