# Generated by Django 3.1.7 on 2021-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0013_auto_20210302_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Color", "color"),
                    ("Size", "size"),
                    ("None", "none"),
                    ("Both", "both"),
                ],
                max_length=177,
            ),
        ),
    ]
