# Generated by Django 3.2.5 on 2021-07-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0021_auto_20210725_1733"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="product",
        ),
    ]
