# Generated by Django 3.2.5 on 2021-07-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0022_remove_comment_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_product.product",
            ),
        ),
    ]
