# Generated by Django 3.2.5 on 2021-07-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0026_alter_product_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="total_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
