# Generated by Django 3.2.5 on 2021-07-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0027_alter_product_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_product.product",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="total_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
