# Generated by Django 3.2.5 on 2021-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0029_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(blank=True, max_length=177, null=True),
        ),
    ]
