# Generated by Django 3.2.5 on 2021-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0030_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=177),
        ),
    ]
