# Generated by Django 3.2.5 on 2021-07-26 08:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0031_alter_size_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
