BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXXXX XXXX BBBBBBBB


BBBBB BBBBBBB
  XXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX


    XXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXX

    XXXX XXXXXXXXXXXX

      XXXX XXXX XXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX

        XXXX XXXX XXXX XXX
        BBB B BB BBBB
        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXX XXXX XXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
               XXXXX
            XXXXXX
          XXXXXX
        BBBBBB
          
          
        XXXXX

        XXXXXX
      XXXXXX

    XXXXXX
    XXXX XXXXX XXX

  XXXXXX
  XXXX XXXXXXXXXXX XXX
BBBBBBBB