# Generated by Django 3.1.7 on 2021-03-02 19:18

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
