BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXXX XXXXXXXX BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB