BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXXXX XXXXXXXX BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBB
            BBBBBBBBBB
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXXX
    XXXXXX
BBBBBBBB