BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBB XXXXXXXX XXXXXXX BBBBBBBB


BBBBB BBBBBBB
  XXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX

    XXXX XXXXXXXXXXXX

      XXXX XXXX XXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX

        XXXX XXXX XXXX XXX
        BBB BBBB BB BBBBB
        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXX XXXX XXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              FFFFFFFF XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXX  
            XXXXXX
            BB BBBBBBBBBBBBBBBBBBB BB BBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                   XXXXXX 
                XXXXXX
            BBBB BBBBBBBBBBBBBBBBBBB BB BBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                   XXXXX 
                XXXXXX
            BBBBB
          XXXXXX
        BBBBBB


      XXXXXX

    XXXXXX
    XXXX XXXXX XXX

  XXXXXX
  XXXX XXXXXXXXXXX XXX
BBBBBBBB