BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB FFFFFFFF XXXXXXX BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXX XXXX
            BBBBB
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX

        BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXXXXXX
            BBBBBBBBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXX XXXX XXX XXXXX XXX XXX XXXXXXXX XXXX XXX XXXXX XXX XXXX XXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        BBBBB
    XXXXXX
BBBBBBBB