BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBB XXXXXXX XXXX BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            XXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB