BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXXXX XXXX BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFF
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB