# Generated by Django 3.1.7 on 2021-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=177)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='1.jpg', upload_to='')),
            ],
        ),
    ]
