BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBB  BBBBBBBB


BBBBB BBBBBBB
    XXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX

    BB BBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXXXXXXXX XXXX XXXXXXXXXXXXX
    BBBB
      XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXXXXX XX XXXXXXXXXXXXX
    BBBBB

    XXXX XXXXXXXXXXXX

      XXXX XXXX XXXXXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX

        XXXX

        XXXX XXXXXXXXX XXX
        XXXXXXX
        BB BBBBBBBBBBBBBB BB BBBBBB
            XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            BBB B BB BBBBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBBBB BB BBBB XXXXXXX BBBBB XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            BBBBBB
            XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              BBB B BB BBBB
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  BB BBBBBBBBBBB BB BBBB XXXXXXX BBBBB XXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX
              BBBBBB
              XXXXXXX

        BBBB BBBBBBBBBBBBBB BB BBBBBBB
            XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            BBB B BB BBBBBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBBBB BB BBBB XXXXXXX BBBBB XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            BBBBBB
            XXXXXXX
        BBBB BBBBBBBBBBBBBB BB BBBBBB
            XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            BBB B BB BBBBBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBBBB BB BBBB XXXXXXX BBBBB XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            BBBBBB
            XXXXXXX
        BBBBB
      
        BB BBBBBBBBBBBBBB BB BBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXXXXX FFFFFFFF XXXXXXXXXX
          BBBB
          XXXXXXXXXX FFFFFFFF XXXXXXXXXX
          BBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        BBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXXXXX FFFFFFFF XXXXXXXXXX
          BBBB
          XXXXXXXXXX FFFFFFFF XXXXXXXXXX
          BBBBB
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBB BBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        BBBBB

        XXXXXXXX

      XXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBXX
          BBBBBBBBBB
          FFFFFFFFFFFFFFF
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX

      BBB B BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX X XXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBB BBBBXX
          BBBBBBBBBB
          FFFFFFFFFFFFFFF
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX

        BBB B BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX X XXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBBB
      BBBBBB

      XXXXXX
    XXXXXX
BBBBBBBB