# Generated by Django 3.1.7 on 2021-02-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop_product", "0010_comment_product"),
        ("shop_cart", "0002_auto_20210228_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_product.variant",
            ),
        ),
    ]
