# Generated by Django 3.1.7 on 2021-03-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_cart", "0006_auto_20210301_1212"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compare",
            name="product",
        ),
        migrations.RemoveField(
            model_name="compare",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Compare",
        ),
    ]
